# Generated by Django 4.2.14 on 2024-12-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_card_cost_alter_cartitem_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.CharField(max_length=8),
        ),
    ]
